---
- name: copy index.html file 
  hosts: all
  become: true
  tasks:
  - name: copy index.html file
    copy:
      src: /opt/ansible/index.html
      dest: /home/ansadmin 
      mode: 755
      owner: appuser22