---
- name: install apache
  hosts: webservers
  become: true
  tasks:
# install httpd app 
  - name: install httpd
    yum:
      name: httpd
      state: installed
# start service
  - name: start service httpd
    service: 
      name: httpd
      state: started