---
- name: uninstall application
  hosts: webservers
  become: true
  tasks:
  - name: stop service 
    service: 
      name: httpd
      state: stopped
  - name: uninstall app 
    yum:
      name: httpd
      state: removed